// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNNe0Dlx8YMBGkv1uql3Cq7T-JhLyVTrw',
    appId: '1:313141347370:web:d100213a30bfaa09866f53',
    messagingSenderId: '313141347370',
    projectId: 'cocpit-90dfb',
    authDomain: 'cocpit-90dfb.firebaseapp.com',
    storageBucket: 'cocpit-90dfb.firebasestorage.app',
    measurementId: 'G-JTQ6ZWT9H4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPnz8z168U3F-EKHQH2sVrmERgApoAeas',
    appId: '1:313141347370:android:7d4e5763e47a8a1c866f53',
    messagingSenderId: '313141347370',
    projectId: 'cocpit-90dfb',
    storageBucket: 'cocpit-90dfb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXPdmgzSeCBsgta26amqJ8uhXhA78Zo1g',
    appId: '1:313141347370:ios:318bc352fd3ac3c7866f53',
    messagingSenderId: '313141347370',
    projectId: 'cocpit-90dfb',
    storageBucket: 'cocpit-90dfb.firebasestorage.app',
    iosClientId: '313141347370-eu32f2uuoqla995srtsdopjsrpi24rbr.apps.googleusercontent.com',
    iosBundleId: 'com.example.techmPractice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXPdmgzSeCBsgta26amqJ8uhXhA78Zo1g',
    appId: '1:313141347370:ios:318bc352fd3ac3c7866f53',
    messagingSenderId: '313141347370',
    projectId: 'cocpit-90dfb',
    storageBucket: 'cocpit-90dfb.firebasestorage.app',
    iosClientId: '313141347370-eu32f2uuoqla995srtsdopjsrpi24rbr.apps.googleusercontent.com',
    iosBundleId: 'com.example.techmPractice',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNNe0Dlx8YMBGkv1uql3Cq7T-JhLyVTrw',
    appId: '1:313141347370:web:5690638fc5fba9fb866f53',
    messagingSenderId: '313141347370',
    projectId: 'cocpit-90dfb',
    authDomain: 'cocpit-90dfb.firebaseapp.com',
    storageBucket: 'cocpit-90dfb.firebasestorage.app',
    measurementId: 'G-PFC969LCB4',
  );
}
